table Dim_geolocation
	lineageTag: 8324616c-cfb3-47bf-87dd-1476ccf700d8

	column geolocation_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 6cbc6859-5d11-4de6-80a3-49d7b616d511
		summarizeBy: none
		sourceColumn: geolocation_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column geolocation_lat
		dataType: int64
		formatString: 0
		lineageTag: d0bda97e-5948-4354-a858-40dfdbd475c7
		summarizeBy: none
		sourceColumn: geolocation_lat

		annotation SummarizationSetBy = Automatic

	column geolocation_lng
		dataType: int64
		formatString: 0
		lineageTag: 9db48ef2-29b8-476f-aff2-b73b341f3046
		summarizeBy: none
		sourceColumn: geolocation_lng

		annotation SummarizationSetBy = Automatic

	column geolocation_city
		dataType: string
		lineageTag: 2dad2f02-14f3-44b4-b6a3-8e5f58a93e31
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: ae317bc0-5fcb-43ef-8656-7e2db5be2370
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	partition Dim_geolocation = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\noeca\OneDrive\Documentos\Triple_Ten_Data_Analysis\Tu Ruta Profecional\Portafolio\archive\olist_geolocation_dataset.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"geolocation_zip_code_prefix", Int64.Type}, {"geolocation_lat", Int64.Type}, {"geolocation_lng", Int64.Type}, {"geolocation_city", type text}, {"geolocation_state", type text}}, "es"),
				    #"Duplicados quitados" = Table.Distinct(#"Tipo de columna cambiado", {"geolocation_zip_code_prefix"})
				in
				  #"Duplicados quitados"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

