table Fact_order_items
	lineageTag: 83d8533c-3d4e-4591-af72-b8b68cc8d3fb

	column order_id
		dataType: string
		lineageTag: 4f3c391a-e5ed-41f7-a8dc-bfc096eed83e
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: e48e678b-4586-452f-a01f-b857ac0adfe4
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 474e3364-eb69-4d58-bf9c-32f385691de4
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 6da0e0d0-1e98-4410-a036-5a36ea33e5a7
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column shipping_limit_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5171ca2f-cf2c-4f18-8d85-c060b31c64e4
		summarizeBy: none
		sourceColumn: shipping_limit_date

		variation Variación
			isDefault
			relationship: c345885d-f303-4144-9ebc-d6697c70d99c
			defaultHierarchy: LocalDateTable_f2ac1aa9-39cd-4c1c-9018-f777436c5952.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column price
		dataType: decimal
		formatString: #,0
		lineageTag: 2af44b1c-8803-4195-915e-3b724c43e787
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column freight_value
		dataType: decimal
		formatString: 0
		lineageTag: 34f17b7a-b592-4824-b4b3-57f8703978b4
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

	partition Fact_order_items = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\noeca\OneDrive\Documentos\Triple_Ten_Data_Analysis\Tu Ruta Profecional\Portafolio\archive\olist_order_items_dataset.csv"), [Delimiter = ",", Columns = 7, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"order_id", type text}, {"order_item_id", Int64.Type}, {"product_id", type text}, {"seller_id", type text}, {"shipping_limit_date", type datetime}, {"price", Int64.Type}, {"freight_value", Int64.Type}}, "es"),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo de columna cambiado",{{"shipping_limit_date", type date}, {"price", Currency.Type}, {"freight_value", Currency.Type}}),
				    #"Columna dividida" = Table.TransformColumns(#"Tipo cambiado", {{"price", each _ / 100, Currency.Type}}),
				    #"Columna dividida1" = Table.TransformColumns(#"Columna dividida", {{"freight_value", each _ / 100, Currency.Type}})
				in
				  #"Columna dividida1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

